_target_: bioemu.shortcuts.training_rollout_denoiser
_partial_: true
eps_t: 0.001  # Final target (for direct jump)
mid_t: 0.786  # Stop point for dpm_solver (matches training)
max_t: 0.99
N: 7          # Match training N_rollout
