score_model:
  _target_: bioemu.shortcuts.DiGConditionalScoreModel
  dim_hidden: 1024
  dim_model: 512
  dim_pair: 256
  dim_single_rep: 64
  dropout: 0.1
  max_distance_relative: 128
  num_buckets: 64
  num_heads: 32
  num_layers: 8
sdes:
  node_orientations:
    _target_: bioemu.shortcuts.DiGSO3SDE
    cache_dir: ~/sampling_so3_cache
    eps_t: 0.001
    l_max: 2000
    num_omega: 2000
    num_sigma: 1000
    omega_exponent: 3
    overwrite_cache: false
    sigma_max: 2.33
    sigma_min: 0.02
    tol: 1.0e-07
  pos:
    _target_: bioemu.shortcuts.CosineVPSDE
    s: 0.008
