molecule: 1fme
method: tae
ckpt_dir: _baseline_
ckpt_path: tae-1FME
date: debug
tags: ['opes']
start_gpu: 0
opes:
  step: 10_000
  sigma: 0.05
  max_seed: 3
  ntomp: 1
analysis:
  gmx: False
  skip_steps: 10
  unit_steps: 10
  equil_temp: 360