molecule: 1fme
method: tica
ckpt_dir: _baseline_
ckpt_path: tica-1FME
date: debug
tags: ['opes']
start_gpu: 0
opes:
  step: 1_000_000
  sigma: 0.5
  max_seed: 3
analysis:
  skip_steps: 1
  unit_steps: 0
  equil_temp: 325