molecule: gtt
method: tda
ckpt_dir: _baseline_
ckpt_path: tda-GTT
date: debug
tags: ['opes']
start_gpu: 0
opes:
  step: 100_000
  sigma: 0.05
  max_seed: 3
analysis:
  skip_steps: 0
  unit_steps: 1
  equil_temp: 340