method: tda
molecule: 1fme
ckpt_dir: _baseline_
ckpt_path: tda-1FME
date: debug
tags: ['opes']
start_gpu: 0
opes:
  ntomp: 1
  step: 10_000
  sigma: 0.05
  max_seed: 3
analysis:
  skip_steps: 0
  unit_steps: 1
  equil_temp: 325