molecule: cln025
method: ours
ckpt_dir: '.'
ckpt_path: 0816_171833-CLN025-f32
date: debug
tags: ['opes']
opes:
  step: 400_000_000
  sigma: 0.05
  max_seed: 3
analysis:
  skip_steps: 50000
  unit_steps: 25000
  equil_temp: 340