molecule: gtt
method: ours
ckpt_dir: .
ckpt_path: 0917_150545-GTT
date: debug
tags: ['opes']
start_gpu: 0
opes:
  step: 500_000_000
  sigma: 0.05
  max_seed: 3
  ntomp: 1
analysis:
  gmx: False
  skip_steps: 50000
  unit_steps: 25000
  equil_temp: 325