molecule: 1fme
method: ours
ckpt_dir: .
# ckpt_path: 0914_150513-1FME
ckpt_path: 0906_145917-1FME
date: debug
tags: ['opes']
start_gpu: 0
opes:
  step: 500_000_000
  sigma: 0.05
  max_seed: 3
  ntomp: 1
analysis:
  gmx: False
  skip_steps: 50000
  unit_steps: 25000
  equil_temp: 325