molecule: 2jof
method: tae
ckpt_dir: _baseline_
ckpt_path: tae-2JOF
date: debug
tags: ['opes']
start_gpu: 0
opes:
  step: 500_000_000
  sigma: 0.05
  max_seed: 3
  ntomp: 1
analysis:
  skip_steps: 50000
  unit_steps: 25000
  equil_temp: 290