molecule: cln025
method: tae
ckpt_dir: _baseline_
ckpt_path: tae-CLN025
date: debug
tags: ['opes']
opes:
  step: 400_000_000
  sigma: 0.05
  max_seed: 3
analysis:
  skip_steps: 50000
  unit_steps: 25000
  equil_temp: 340