molecule: 2jof
method: tica
ckpt_dir: _baseline_
ckpt_path: tica-2JOF
date: debug
tags: ['opes']
start_gpu: 0
opes:
  step: 500_000_000
  sigma: 0.05
  max_seed: 3
  ntomp: 1
analysis:
  gmx: False
  skip_steps: 50000
  unit_steps: 25000
  equil_temp: 290
  interval: 21600
  plots: all