molecule: cln025
method: tica
ckpt_dir: _baseline_
ckpt_path: tica-CLN025
date: debug
tags: ['opes']
start_gpu: 0
opes:
  step: 500_000_000
  sigma: 0.05
  max_seed: 3
  ntomp: 1
analysis:
  gmx: False
  skip_steps: 50000
  unit_steps: 25000
  equil_temp: 340
  interval: 30
  plots: all